local ADDONNAME, ns = ...
if not ns then
    -- Namespace not available in Wrath, so we fallback:
    _G[ADDONNAME] = _G[ADDONNAME] or {}
    ns = _G[ADDONNAME]
end

-- Localization table
local L = {}
ns.L = L

-- English fallback table
ns.enUS = {}

-- Current locale -- returns "enUS", "frFR", "deDE", "esES", etc.
local locale = GetLocale() or "enUS"

-- To test a specific locale, hard-code it here and uncomment the line.
--locale = "deDE"

-- Metatable for automatic fallback with debug logging
setmetatable(L, {
    __index = function(t, k)
        local localeTable = ns[locale]
        if localeTable and localeTable[k] then
            rawset(t, k, localeTable[k])
            return localeTable[k]
        elseif ns.enUS[k] then
            --print("Fallback to enUS for key:", k)
            rawset(t, k, ns.enUS[k])
            return ns.enUS[k]
        else
            --print("Missing translation for key:", k)
            rawset(t, k, k)
            return k
        end
    end
})

-- English
ns["enUS"] = {
    SLOTS = {
        ammo = "ammo",
        head = "head",
        neck = "neck",
        shoulder = "shoulder",
        shirt = "shirt",
        chest = "chest",
        waist = "waist",
        legs = "legs",
        feet = "feet",
        wrist = "wrist",
        hands = "hands",
        finger0 = "finger #1",
        finger1 = "finger #2",
        trinket0 = "trinket #1",
        trinket1 = "trinket #2",
        back = "back",
        mainhand = "main hand",
        secondaryhand = "off-hand",
        ranged = "ranged",
        tabard = "tabard",
    },

    -- These are the names of the buffs you get from eating cooked food or applying a scroll
    SCROLL_BUFFS = { ["Well Fed"]=1, ["Spirit"]=1, ["Armor"]=1, ["Intellect"]=1, ["Agility"]=1, ["Stamina"]=1, ["Strength"]=1, },

    title = "THE IRONMAN CHALLENGE",
    prefix = "IRONMAN: ",
    description = function() return
        "Hardcore, self-found, only white or gray gear, no primary professions, no potions, no healthstones, no food or scroll buffs, no external buffs" ..
        (IronmanUserData.AllowMaps    and "" or ", no maps")    ..
        (IronmanUserData.AllowTalents and "" or ", no talents") ..
        (IronmanUserData.AllowPets    and "" or ", no pets")    ..
        (IronmanUserData.AllowMaps    and ", maps OK"    or "") ..
        (IronmanUserData.AllowTalents and ", talents OK" or "") ..
        (IronmanUserData.AllowPets    and ", pets OK"    or "") ..
        "." end,
    currently_on = "currently ON",
    currently_off = "currently OFF",
    cmdln_n = "Checks every {N} seconds (15 by default)",
    cmdln_on_off = "Start/stop periodic checking",
    cmdln_maps = "Show/hide map & minimap",
    cmdln_pets = "Allow/forbid pets",
    cmdln_profs = "Allow/forbid secondary professions",
    maps_on = "Pets are now allowed",
    maps_off = "Pets are now forbidden",
    pets_on = "Pets are now allowed",
    pets_off = "Pets are now forbidden",
    talents_on = "Talents are now allowed",
    talents_off = "Talents are now forbidden",
    disclaimer = "Due to the limited nature of the WoW API, it's difficult to determine whether a given buff is OK or not. If someone else buffs you, the addon can tell you about that; and it can tell you to remove scroll buffs. But it cannot warn you about buffs from alchemy. HOTs from other players are considered buffs, so it will warn you about those.",
    err_seconds_ij = function(i, j) return "Seconds must be between " .. i .. " and " .. j end,
    checking_every_n = function(n) return "Now checking every " .. n .. " seconds" end,
    checking_off_s = function(s) return "Checking turned off, type " .. s .. " to turn it on" end,
    checking_on_n = function(n) return "Checking every " .. n .. " seconds" end,
    checking_on = "Checking on",
    checking_off = "Checking off",
    type_s_for_more_info = function(s) return "Type " .. s .. " for more info" end,
    err_unequip_s_s = function(slotname, link) return "Unequip " .. slotname .. " slot " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Unequip enchanted " .. slotname .. " slot " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "You cannot use " .. link end,
    err_reset_talents = "Reset your talents",
    err_unlearn_n_profs = function(n) return n==1 and ("Unlearn your primary profession") or ("Unlearn your primary professions") end,
    err_buff_external = function(s) return "Remove external buff: " .. s end,
    err_buff_disallowed = function(s) return "Remove disallowed buff: " .. s end,
    err_you_died = "You have died",
    err_no_mail = "You cannot use mail",
    err_no_ah = "You cannot use the auction house",
    err_pet = "No pets allowed",
    err_unload_addon = function(name) return "You must unload the \"" .. name .. "\" addon" end,
}

-- German
ns["deDE"] = {
    SLOTS = {
        ammo = "Munition",
        head = "Kopf",
        neck = "Hals",
        shoulder = "Schulter",
        shirt = "Hemd",
        chest = "Brust",
        waist = "Taille",
        legs = "Beine",
        feet = "Füße",
        wrist = "Handgelenke",
        hands = "Hände",
        finger0 = "Finger #1",
        finger1 = "Finger #2",
        trinket0 = "Schmuckstück #1",
        trinket1 = "Schmuckstück #2",
        back = "Rücken",
        mainhand = "Waffenhand",
        secondaryhand = "Schildhand",
        ranged = "Distanz",
        tabard = "Wappenrock",
    },

    SCROLL_BUFFS = { ["Satt"]=1, ["Willenskraft"]=1, ["Rüstung"]=1, ["Intelligenz"]=1, ["Beweglichkeit"]=1, ["Ausdauer"]=1, ["Stärke"]=1, },

    title = "DIE IRONMAN-HERAUSFORDERUNG",
    prefix = "IRONMAN: ",
    description = "Hardcore, self-found (kein Auktionshaus, keine Post, kein Handeln), nur weiße oder graue Ausrüstung, keine Talente, keine Begleiter, keine Primärberufe, keine Tränke, keine Gesundheitssteine, keine Nahrungs- oder Schriftrollen-Buffs, keine externen Buffs, Selbstbuffs sind erlaubt.",
    currently_on = "derzeit AKTIV",
    currently_off = "derzeit INAKTIV",
    cmdln_n = "Überprüft alle {N} Sekunden (standardmäßig 15)",
    cmdln_on_off = "Periodische Überprüfung starten/stoppen",
    cmdln_pets = "Begleiter erlauben/verbieten",
    cmdln_profs = "Sekundärberufe erlauben/verbieten",
    pets_on = "Begleiter sind jetzt erlaubt",
    pets_off = "Begleiter sind jetzt verboten",
    profs_on = "Sekundärberufe sind jetzt erlaubt",
    profs_off = "Sekundärberufe sind jetzt verboten",
    disclaimer = "Aufgrund der eingeschränkten WoW-API ist es schwierig festzustellen, ob ein Buff erlaubt ist oder nicht. Wenn dich jemand anderes bufft, kann das Addon dich darauf hinweisen; und es kann dir sagen, dass du Schriftrollen-Buffs entfernen musst. Aber es kann dich nicht vor Alchemie-Buffs warnen. Heilungen über Zeit von anderen Spielern gelten als Buffs, daher wird es dich auch darauf hinweisen.",
    err_seconds_ij = function(i, j) return "Sekunden müssen zwischen " .. i .. " und " .. j .. " liegen" end,
    checking_every_n = function(n) return "Überprüfung alle " .. n .. " Sekunden" end,
    checking_on = "Überprüfung eingeschaltet",
    checking_off = "Überprüfung ausgeschaltet",
    init_checking_off_s = function(s) return "Initialisiert, Überprüfung ausgeschaltet, tippe " .. s .. " um sie einzuschalten" end,
    init_checking_on_n = function(n) return "Initialisiert, Überprüfung alle " .. n .. " Sekunden" end,
    type_s_for_more_info = function(s) return "Tippe " .. s .. " für mehr Informationen" end,
    err_unequip_s_s = function(slotname, link) return "Lege " .. slotname .. " Slot " .. (link or '') .. " ab" end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Lege verzauberten " .. slotname .. " Slot " .. (link or '') .. " ab" end,
    err_you_cannot_use_s = function(link) return "Du kannst " .. link .. " nicht verwenden" end,
    err_reset_talents = "Setze deine Talente zurück",
    err_unlearn_n_profs = function(n) return n==1 and ("Lerne deinen Primärberuf ab") or ("Lerne deine Primärberufe ab") end,
    err_buff_external = function(s) return "Entferne externen Buff: " .. s end,
    err_buff_disallowed = function(s) return "Entferne verbotenen Buff: " .. s end,
    err_you_died = "Du bist gestorben",
    err_no_mail = "Du kannst keine Post benutzen",
    err_no_ah = "Du kannst das Auktionshaus nicht benutzen",
    err_pet = "Keine Begleiter erlaubt",
}

-- Spanish (Spain)
ns["esES"] = {
    SLOTS = {
        ammo = "munición",
        head = "cabeza",
        neck = "cuello",
        shoulder = "hombros",
        shirt = "camisa",
        chest = "pecho",
        waist = "cintura",
        legs = "piernas",
        feet = "pies",
        wrist = "muñeca",
        hands = "manos",
        finger0 = "dedo #1",
        finger1 = "dedo #2",
        trinket0 = "abrecartas #1",
        trinket1 = "abrecartas #2",
        back = "espalda",
        mainhand = "mano principal",
        secondaryhand = "mano izquierda",
        ranged = "a distancia",
        tabard = "tabardo",
    },

    SCROLL_BUFFS = { ["Bien alimentado"]=1, ["Espíritu"]=1, ["Armadura"]=1, ["Intelecto"]=1, ["Agilidad"]=1, ["Aguante"]=1, ["Fuerza"]=1, },

    title = "EL DESAFÍO IRONMAN",
    prefix = "IRONMAN: ",
    description = "Hardcore, auto-suficiente (sin subasta, sin correo, sin comercio), solo equipo blanco o gris, sin talentos, sin mascotas, sin profesiones primarias, sin pociones, sin piedras de salud, sin beneficios de comida o pergaminos, sin beneficios externos, los hechizos de auto-buff están permitidos.",
    currently_on = "actualmente ACTIVADO",
    currently_off = "actualmente DESACTIVADO",
    cmdln_n = "Comprueba cada {N} segundos (15 por defecto)",
    cmdln_on_off = "Iniciar/detener comprobación periódica",
    cmdln_pets = "Permitir/prohibir mascotas",
    cmdln_profs = "Permitir/prohibir profesiones secundarias",
    pets_on = "Las mascotas están ahora permitidas",
    pets_off = "Las mascotas están ahora prohibidas",
    profs_on = "Las profesiones secundarias están ahora permitidas",
    profs_off = "Las profesiones secundarias están ahora prohibidas",
    disclaimer = "Debido a la naturaleza limitada de la API de WoW, es difícil determinar si un beneficio está permitido o no. Si otro jugador te da un beneficio, el addon puede avisarte; y puede decirte que elimines beneficios de pergaminos. Pero no puede avisarte sobre beneficios de alquimia. Las sanaciones periódicas de otros jugadores se consideran beneficios, por lo que también te avisará sobre ellos.",
    err_seconds_ij = function(i, j) return "Los segundos deben estar entre " .. i .. " y " .. j end,
    checking_every_n = function(n) return "Comprobando cada " .. n .. " segundos" end,
    checking_on = "Comprobación activada",
    checking_off = "Comprobación desactivada",
    init_checking_off_s = function(s) return "Inicializado, comprobación desactivada, escribe " .. s .. " para activarla" end,
    init_checking_on_n = function(n) return "Inicializado, comprobando cada " .. n .. " segundos" end,
    type_s_for_more_info = function(s) return "Escribe " .. s .. " para más información" end,
    err_unequip_s_s = function(slotname, link) return "Quítate la ranura " .. slotname .. " " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Quítate la ranura encantada " .. slotname .. " " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "No puedes usar " .. link end,
    err_reset_talents = "Reinicia tus talentos",
    err_unlearn_n_profs = function(n) return n==1 and ("Olvida tu profesión primaria") or ("Olvida tus profesiones primarias") end,
    err_buff_external = function(s) return "Quita beneficio externo: " .. s end,
    err_buff_disallowed = function(s) return "Quita beneficio prohibido: " .. s end,
    err_you_died = "Has muerto",
    err_no_mail = "No puedes usar el correo",
    err_no_ah = "No puedes usar la casa de subastas",
    err_pet = "No se permiten mascotas",
}

-- French
ns["frFR"] = {
    SLOTS = {
        ammo = "munitions",
        head = "tête",
        neck = "cou",
        shoulder = "épaules",
        shirt = "chemise",
        chest = "torse",
        waist = "taille",
        legs = "jambes",
        feet = "pieds",
        wrist = "poignets",
        hands = "mains",
        finger0 = "doigt #1",
        finger1 = "doigt #2",
        trinket0 = "bijou #1",
        trinket1 = "bijou #2",
        back = "dos",
        mainhand = "main droite",
        secondaryhand = "main gauche",
        ranged = "à distance",
        tabard = "tabard",
    },

    SCROLL_BUFFS = { ["Bien nourri"]=1, ["Esprit"]=1, ["Armure"]=1, ["Intelligence"]=1, ["Agilité"]=1, ["Endurance"]=1, ["Force"]=1, },

    title = "LE DÉFI IRONMAN",
    prefix = "IRONMAN : ",
    description = "Hardcore, auto-suffisant (pas d’hôtel des ventes, pas de courrier, pas d’échanges), seulement équipement blanc ou gris, pas de talents, pas d’animaux, pas de professions principales, pas de potions, pas de pierres de soins, pas de bonus de nourriture ou de parchemins, pas de bonus externes, les sorts de self-buff sont autorisés.",
    currently_on = "actuellement ACTIVÉ",
    currently_off = "actuellement DÉSACTIVÉ",
    cmdln_n = "Vérifie toutes les {N} secondes (15 par défaut)",
    cmdln_on_off = "Démarrer/arrêter la vérification périodique",
    cmdln_pets = "Autoriser/interdire les familiers",
    cmdln_profs = "Autoriser/interdire les professions secondaires",
    pets_on = "Les familiers sont maintenant autorisés",
    pets_off = "Les familiers sont maintenant interdits",
    profs_on = "Les professions secondaires sont maintenant autorisées",
    profs_off = "Les professions secondaires sont maintenant interdites",
    disclaimer = "En raison de la nature limitée de l’API de WoW, il est difficile de déterminer si un bonus est autorisé ou non. Si quelqu’un d’autre vous donne un bonus, l’addon peut vous en informer ; et il peut vous dire de retirer les bonus de parchemins. Mais il ne peut pas vous avertir des bonus provenant de l’alchimie. Les soins sur la durée des autres joueurs sont considérés comme des bonus, donc il vous en avertira également.",
    err_seconds_ij = function(i, j) return "Les secondes doivent être comprises entre " .. i .. " et " .. j end,
    checking_every_n = function(n) return "Vérification toutes les " .. n .. " secondes" end,
    checking_on = "Vérification activée",
    checking_off = "Vérification désactivée",
    init_checking_off_s = function(s) return "Initialisé, vérification désactivée, tapez " .. s .. " pour l’activer" end,
    init_checking_on_n = function(n) return "Initialisé, vérification toutes les " .. n .. " secondes" end,
    type_s_for_more_info = function(s) return "Tapez " .. s .. " pour plus d’informations" end,
    err_unequip_s_s = function(slotname, link) return "Retirez l’emplacement " .. slotname .. " " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Retirez l’emplacement enchanté " .. slotname .. " " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "Vous ne pouvez pas utiliser " .. link end,
    err_reset_talents = "Réinitialisez vos talents",
    err_unlearn_n_profs = function(n) return n==1 and ("Oubliez votre profession principale") or ("Oubliez vos professions principales") end,
    err_buff_external = function(s) return "Retirez le bonus externe : " .. s end,
    err_buff_disallowed = function(s) return "Retirez le bonus interdit : " .. s end,
    err_you_died = "Vous êtes mort",
    err_no_mail = "Vous ne pouvez pas utiliser le courrier",
    err_no_ah = "Vous ne pouvez pas utiliser l’hôtel des ventes",
    err_pet = "Aucun familier autorisé",
}

-- Italian
ns["itIT"] = {
    SLOTS = {
        ammo = "munizioni",
        head = "testa",
        neck = "collo",
        shoulder = "spalle",
        shirt = "camicia",
        chest = "petto",
        waist = "vita",
        legs = "gambe",
        feet = "piedi",
        wrist = "polsi",
        hands = "mani",
        finger0 = "dito #1",
        finger1 = "dito #2",
        trinket0 = "monile #1",
        trinket1 = "monile #2",
        back = "schiena",
        mainhand = "mano primaria",
        secondaryhand = "mano secondaria",
        ranged = "a distanza",
        tabard = "tabardo",
    },

    SCROLL_BUFFS = { ["Ben nutrito"]=1, ["Spirito"]=1, ["Armatura"]=1, ["Intelletto"]=1, ["Agilità"]=1, ["Tempra"]=1, ["Forza"]=1, },

    title = "LA SFIDA IRONMAN",
    prefix = "IRONMAN: ",
    description = "Hardcore, auto-sufficiente (niente casa d’aste, niente posta, niente scambi), solo equipaggiamento bianco o grigio, niente talenti, niente mascotte, niente professioni primarie, niente pozioni, niente pietre della salute, niente benefici da cibo o pergamene, niente benefici esterni, gli incantesimi di auto-buff sono consentiti.",
    currently_on = "attualmente ATTIVO",
    currently_off = "attualmente DISATTIVO",
    cmdln_n = "Controlla ogni {N} secondi (15 di default)",
    cmdln_on_off = "Avvia/ferma controllo periodico",
    cmdln_pets = "Permetti/vieta mascotte",
    cmdln_profs = "Permetti/vieta professioni secondarie",
    pets_on = "Le mascotte sono ora permesse",
    pets_off = "Le mascotte sono ora vietate",
    profs_on = "Le professioni secondarie sono ora permesse",
    profs_off = "Le professioni secondarie sono ora vietate",
    disclaimer = "A causa della natura limitata dell’API di WoW, è difficile determinare se un beneficio è consentito o meno. Se qualcun altro ti fornisce un beneficio, l’addon può avvisarti; e può dirti di rimuovere i benefici da pergamena. Ma non può avvisarti sui benefici da alchimia. Le cure periodiche di altri giocatori sono considerate benefici, quindi ti avviserà anche di quelle.",
    err_seconds_ij = function(i, j) return "I secondi devono essere tra " .. i .. " e " .. j end,
    checking_every_n = function(n) return "Controllo ogni " .. n .. " secondi" end,
    checking_on = "Controllo attivato",
    checking_off = "Controllo disattivato",
    init_checking_off_s = function(s) return "Inizializzato, controllo disattivato, digita " .. s .. " per attivarlo" end,
    init_checking_on_n = function(n) return "Inizializzato, controllo ogni " .. n .. " secondi" end,
    type_s_for_more_info = function(s) return "Digita " .. s .. " per maggiori informazioni" end,
    err_unequip_s_s = function(slotname, link) return "Rimuovi slot " .. slotname .. " " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Rimuovi slot incantato " .. slotname .. " " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "Non puoi usare " .. link end,
    err_reset_talents = "Reimposta i tuoi talenti",
    err_unlearn_n_profs = function(n) return n==1 and ("Dimentica la tua professione primaria") or ("Dimentica le tue professioni primarie") end,
    err_buff_external = function(s) return "Rimuovi beneficio esterno: " .. s end,
    err_buff_disallowed = function(s) return "Rimuovi beneficio vietato: " .. s end,
    err_you_died = "Sei morto",
    err_no_mail = "Non puoi usare la posta",
    err_no_ah = "Non puoi usare la casa d’aste",
    err_pet = "Nessuna mascotte consentita",
}

-- Russian
ns["ruRU"] = {
    SLOTS = {
        ammo = "патроны",
        head = "голова",
        neck = "шея",
        shoulder = "плечи",
        shirt = "рубашка",
        chest = "грудь",
        waist = "пояс",
        legs = "ноги",
        feet = "ступни",
        wrist = "запястья",
        hands = "кисти",
        finger0 = "палец #1",
        finger1 = "палец #2",
        trinket0 = "аксессуар #1",
        trinket1 = "аксессуар #2",
        back = "спина",
        mainhand = "правая рука",
        secondaryhand = "левая рука",
        ranged = "дальний бой",
        tabard = "гербовая накидка",
    },

    SCROLL_BUFFS = { ["Сытость"]=1, ["Дух"]=1, ["Броня"]=1, ["Интеллект"]=1, ["Ловкость"]=1, ["Выносливость"]=1, ["Сила"]=1, },

    title = "ИСПЫТАНИЕ IRONMAN",
    prefix = "IRONMAN: ",
    description = "Хардкор, сам себе добытчик (без аукциона, без почты, без торговли), только белое или серое снаряжение, без талантов, без питомцев, без основных профессий, без зелий, без камней здоровья, без эффектов еды и свитков, без внешних баффов, собственные заклинания-бaффы разрешены.",
    currently_on = "сейчас ВКЛЮЧЕНО",
    currently_off = "сейчас ВЫКЛЮЧЕНО",
    cmdln_n = "Проверка каждые {N} секунд (по умолчанию 15)",
    cmdln_on_off = "Запустить/остановить периодическую проверку",
    cmdln_pets = "Разрешить/запретить питомцев",
    cmdln_profs = "Разрешить/запретить вторичные профессии",
    pets_on = "Питомцы теперь разрешены",
    pets_off = "Питомцы теперь запрещены",
    profs_on = "Вторичные профессии теперь разрешены",
    profs_off = "Вторичные профессии теперь запрещены",
    disclaimer = "Из-за ограничений API WoW трудно определить, разрешен ли данный бафф. Если другой игрок наложит на вас бафф, аддон сможет это показать; и он сообщит, что нужно снять баффы от свитков. Но он не сможет предупредить о баффах алхимии. Эффекты периодического исцеления от других игроков считаются баффами, поэтому он тоже предупредит об этом.",
    err_seconds_ij = function(i, j) return "Секунды должны быть между " .. i .. " и " .. j end,
    checking_every_n = function(n) return "Проверка каждые " .. n .. " секунд" end,
    checking_on = "Проверка включена",
    checking_off = "Проверка выключена",
    init_checking_off_s = function(s) return "Инициализация завершена, проверка отключена, введите " .. s .. " чтобы включить" end,
    init_checking_on_n = function(n) return "Инициализация завершена, проверка каждые " .. n .. " секунд" end,
    type_s_for_more_info = function(s) return "Введите " .. s .. " для подробной информации" end,
    err_unequip_s_s = function(slotname, link) return "Снимите предмет в слоте " .. slotname .. " " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Снимите зачарованный предмет в слоте " .. slotname .. " " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "Вы не можете использовать " .. link end,
    err_reset_talents = "Сбросьте свои таланты",
    err_unlearn_n_profs = function(n) return n==1 and ("Забудьте свою основную профессию") or ("Забудьте свои основные профессии") end,
    err_buff_external = function(s) return "Удалите внешний бафф: " .. s end,
    err_buff_disallowed = function(s) return "Удалите запрещенный бафф: " .. s end,
    err_you_died = "Вы умерли",
    err_no_mail = "Вы не можете пользоваться почтой",
    err_no_ah = "Вы не можете пользоваться аукционом",
    err_pet = "Питомцы запрещены",
}

-- Traditional Chinese
ns["zhTW"] = {
    SLOTS = {
        ammo = "彈藥",
        head = "頭部",
        neck = "頸部",
        shoulder = "肩膀",
        shirt = "襯衫",
        chest = "胸部",
        waist = "腰部",
        legs = "腿部",
        feet = "腳部",
        wrist = "手腕",
        hands = "手",
        finger0 = "手指 #1",
        finger1 = "手指 #2",
        trinket0 = "飾品 #1",
        trinket1 = "飾品 #2",
        back = "背部",
        mainhand = "主手",
        secondaryhand = "副手",
        ranged = "遠程",
        tabard = "外袍",
    },

    SCROLL_BUFFS = { ["進食充分"]=1, ["精神"]=1, ["護甲"]=1, ["智力"]=1, ["敏捷"]=1, ["耐力"]=1, ["力量"]=1, },

    title = "鐵人挑戰",
    prefix = "IRONMAN: ",
    description = "硬派，自給自足（無拍賣場、無郵件、無交易），只能使用白色或灰色裝備，無天賦，無寵物，無主要專業，無藥水，無治療石，無食物或卷軸增益，無外部增益，允許自我增益法術。",
    currently_on = "目前已開啟",
    currently_off = "目前已關閉",
    cmdln_n = "每 {N} 秒檢查一次（預設為15）",
    cmdln_on_off = "開始/停止定期檢查",
    cmdln_pets = "允許/禁止寵物",
    cmdln_profs = "允許/禁止次要專業",
    pets_on = "現在允許寵物",
    pets_off = "現在禁止寵物",
    profs_on = "現在允許次要專業",
    profs_off = "現在禁止次要專業",
    disclaimer = "由於 WoW API 的限制，很難判斷某個增益是否允許。如果其他玩家給你增益，插件可以告訴你；也可以提醒你移除卷軸增益。但它無法提醒你關於鍊金的增益。其他玩家的持續治療效果也算增益，因此也會提醒你。",
    err_seconds_ij = function(i, j) return "秒數必須在 " .. i .. " 和 " .. j .. " 之間" end,
    checking_every_n = function(n) return "現在每 " .. n .. " 秒檢查一次" end,
    checking_on = "檢查已開啟",
    checking_off = "檢查已關閉",
    init_checking_off_s = function(s) return "已初始化，檢查已關閉，輸入 " .. s .. " 以開啟" end,
    init_checking_on_n = function(n) return "已初始化，每 " .. n .. " 秒檢查一次" end,
    type_s_for_more_info = function(s) return "輸入 " .. s .. " 以取得更多資訊" end,
    err_unequip_s_s = function(slotname, link) return "卸下 " .. slotname .. " 插槽 " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "卸下附魔的 " .. slotname .. " 插槽 " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "你不能使用 " .. link end,
    err_reset_talents = "重置你的天賦",
    err_unlearn_n_profs = function(n) return n==1 and ("遺忘你的主要專業") or ("遺忘你的主要專業") end,
    err_buff_external = function(s) return "移除外部增益：" .. s end,
    err_buff_disallowed = function(s) return "移除禁止的增益：" .. s end,
    err_you_died = "你已經死亡",
    err_no_mail = "你不能使用郵件",
    err_no_ah = "你不能使用拍賣場",
    err_pet = "不允許寵物",
}

-- Korean
ns["koKR"] = {
    SLOTS = {
        ammo = "탄약",
        head = "머리",
        neck = "목",
        shoulder = "어깨",
        shirt = "속옷",
        chest = "가슴",
        waist = "허리",
        legs = "다리",
        feet = "발",
        wrist = "손목",
        hands = "손",
        finger0 = "손가락 #1",
        finger1 = "손가락 #2",
        trinket0 = "장신구 #1",
        trinket1 = "장신구 #2",
        back = "등",
        mainhand = "주장비",
        secondaryhand = "보조장비",
        ranged = "원거리",
        tabard = "겉옷",
    },

    SCROLL_BUFFS = { ["배불리 먹음"]=1, ["정신력"]=1, ["방어도"]=1, ["지능"]=1, ["민첩성"]=1, ["체력"]=1, ["힘"]=1, },

    title = "아이언맨 도전",
    prefix = "IRONMAN: ",
    description = "하드코어, 자급자족 (경매장 없음, 우편 없음, 거래 없음), 흰색/회색 장비만 사용, 특성 없음, 펫 없음, 전문 기술 없음, 물약 없음, 생명석 없음, 음식 또는 주문서 버프 없음, 외부 버프 없음, 자기 강화 주문은 허용.",
    currently_on = "현재 켜짐",
    currently_off = "현재 꺼짐",
    cmdln_n = "{N}초마다 확인 (기본값 15)",
    cmdln_on_off = "주기적 확인 시작/중지",
    cmdln_pets = "펫 허용/금지",
    cmdln_profs = "보조 기술 허용/금지",
    pets_on = "펫이 이제 허용됨",
    pets_off = "펫이 이제 금지됨",
    profs_on = "보조 기술이 이제 허용됨",
    profs_off = "보조 기술이 이제 금지됨",
    disclaimer = "WoW API의 한계로 인해, 특정 버프가 허용되는지 판단하기 어렵습니다. 다른 사람이 버프를 걸면 애드온이 알려줄 수 있고, 주문서 버프 제거도 알려줄 수 있습니다. 하지만 연금술 버프는 경고하지 못합니다. 다른 플레이어의 HOT(지속 치유)는 버프로 간주되므로 이에 대해서도 경고합니다.",
    err_seconds_ij = function(i, j) return "초는 " .. i .. "과 " .. j .. " 사이여야 합니다" end,
    checking_every_n = function(n) return n .. "초마다 확인" end,
    checking_on = "확인 켜짐",
    checking_off = "확인 꺼짐",
    init_checking_off_s = function(s) return "초기화됨, 확인 꺼짐, " .. s .. " 입력 시 켜짐" end,
    init_checking_on_n = function(n) return "초기화됨, " .. n .. "초마다 확인" end,
    type_s_for_more_info = function(s) return s .. " 입력 시 자세한 정보" end,
    err_unequip_s_s = function(slotname, link) return slotname .. " 슬롯 해제 " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "마법부여된 " .. slotname .. " 슬롯 해제 " .. (link or '') end,
    err_you_cannot_use_s = function(link) return link .. "을(를) 사용할 수 없습니다" end,
    err_reset_talents = "특성을 초기화하세요",
    err_unlearn_n_profs = function(n) return n==1 and ("주요 전문 기술을 잊으세요") or ("주요 전문 기술을 잊으세요") end,
    err_buff_external = function(s) return "외부 버프 제거: " .. s end,
    err_buff_disallowed = function(s) return "허용되지 않는 버프 제거: " .. s end,
    err_you_died = "당신은 죽었습니다",
    err_no_mail = "우편을 사용할 수 없습니다",
    err_no_ah = "경매장을 사용할 수 없습니다",
    err_pet = "펫은 허용되지 않습니다",
}
