local ADDONNAME, ns = ...
if not ns then
    -- Namespace not available in Wrath, so we fallback:
    _G[ADDONNAME] = _G[ADDONNAME] or {}
    ns = _G[ADDONNAME]
end

-- Localization table
local L = {}
ns.L = L

-- English fallback table
ns.enUS = {}

-- Current locale -- returns "enUS", "frFR", "deDE", "esES", etc.
local locale = GetLocale() or "enUS"

-- To test a specific locale, hard-code it here and uncomment the line.
--locale = "deDE"

-- Metatable for automatic fallback with debug logging
setmetatable(L, {
    __index = function(t, k)
        local localeTable = ns[locale]
        if localeTable and localeTable[k] then
            rawset(t, k, localeTable[k])
            return localeTable[k]
        elseif ns.enUS[k] then
            --print("Fallback to enUS for key:", k)
            rawset(t, k, ns.enUS[k])
            return ns.enUS[k]
        else
            --print("Missing translation for key:", k)
            rawset(t, k, k)
            return k
        end
    end
})

ns["enUS"] = {
    SLOTS = {
        ammo = "ammo",
        head = "head",
        neck = "neck",
        shoulder = "shoulder",
        shirt = "shirt",
        chest = "chest",
        waist = "waist",
        legs = "legs",
        feet = "feet",
        wrist = "wrist",
        hands = "hands",
        finger0 = "finger #1",
        finger1 = "finger #2",
        trinket0 = "trinket #1",
        trinket1 = "trinket #2",
        back = "back",
        mainhand = "main hand",
        secondaryhand = "off-hand",
        ranged = "ranged",
        tabard = "tabard",
    },

    SCROLL_BUFFS = { ["Well Fed"]=1, ["Spirit"]=1, ["Armor"]=1, ["Intellect"]=1, ["Agility"]=1, ["Stamina"]=1, ["Strength"]=1, },
    PRIMARY_PROFESSIONS = { ["Alchemy"]=1, ["Blacksmithing"]=1, ["Enchanting"]=1, ["Engineering"]=1, ["Herbalism"]=1, ["Inscription"]=1, ["Jewelcrafting"]=1, ["Leatherworking"]=1, ["Mining"]=1, ["Skinning"]=1, ["Tailoring"]=1, },

    title = "THE IRONMAN CHALLENGE",
    prefix = "IRONMAN: ",
    description = "Hardcore, self-found (no auction house, no mail, no trading), only white or gray gear, no talents, no pets, no primary professions, no potions, no healthstones, no food or scroll buffs, no external buffs, self-buff spells are OK.",
    currently_on = "currently ON",
    currently_off = "currently OFF",
    cmdln_n = "Checks every {N} seconds (15 by default)",
    cmdln_on_off = "Start/stop periodic checking",
    cmdln_pets = "Allow/forbid pets",
    cmdln_profs = "Allow/forbid secondary professions",
    pets_on = "Pets are now allowed",
    pets_off = "Pets are now forbidden",
    profs_on = "Secondary professions are now allowed",
    profs_off = "Secondary professions are now forbidden",
    disclaimer = "Due to the limited nature of the WoW API, it's difficult to determine whether a given buff is OK or not. If someone else buffs you, the addon can tell you about that; and it can tell you to remove scroll buffs. But it cannot warn you about buffs from alchemy. HOTs from other players are considered buffs, so it will warn you about those.",
    err_seconds_ij = function(i, j) return "Seconds must be between " .. i .. " and " .. j end,
    checking_every_n = function(n) return "Now checking every " .. n .. " seconds" end,
    checking_on = "Checking on",
    checking_off = "Checking off",
    init_checking_off_s = function(s) return "Initialized, checking turned off, type " .. s .. " to turn it on" end,
    init_checking_on_n = function(n) return "Initialized, checking every " .. n .. " seconds" end,
    type_s_for_more_info = function(s) return "Type " .. s .. " for more info" end,
    err_unequip_s_s = function(slotname, link) return "Unequip " .. slotname .. " slot " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Unequip enchanted " .. slotname .. " slot " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "You cannot use " .. link end,
    err_reset_talents = "Reset your talents",
    err_unlearn_n_profs = function(n) return n==1 and ("Unlearn your primary profession") or ("Unlearn your primary professions") end,
    err_unlearn_n_sec_profs = function(n) return n==1 and ("Unlearn your secondary profession") or ("Unlearn your secondary professions") end,
    err_buff_external = function(s) return "Remove external buff: " .. s end,
    err_buff_disallowed = function(s) return "Remove disallowed buff: " .. s end,
    err_you_died = "You have died",
    err_no_mail = "You cannot use mail",
    err_no_ah = "You cannot use the auction house",
    err_pet = "No pets allowed",
}

ns["deDE"] = {
    SLOTS = {
        ammo = "Munition",
        head = "Kopf",
        neck = "Hals",
        shoulder = "Schulter",
        shirt = "Hemd",
        chest = "Brust",
        waist = "Taille",
        legs = "Beine",
        feet = "Füße",
        wrist = "Handgelenke",
        hands = "Hände",
        finger0 = "Finger 1",
        finger1 = "Finger 2",
        trinket0 = "Schmuck 1",
        trinket1 = "Schmuck 2",
        back = "Rücken",
        mainhand = "Waffenhand",
        secondaryhand = "Schildhand",
        ranged = "Distanz",
        tabard = "Wappenrock",
    },

    SCROLL_BUFFS = { ["Satt"]=1, ["Willenskraft"]=1, ["Rüstung"]=1, ["Intelligenz"]=1, ["Beweglichkeit"]=1, ["Ausdauer"]=1, ["Stärke"]=1, },
    PRIMARY_PROFESSIONS = { ["Alchimie"]=1, ["Schmiedekunst"]=1, ["Verzauberkunst"]=1, ["Ingenieurskunst"]=1, ["Kräuterkunde"]=1, ["Inschriftenkunde"]=1, ["Juwelenschleifen"]=1, ["Lederverarbeitung"]=1, ["Bergbau"]=1, ["Kürschnerei"]=1, ["Schneiderei"]=1, },

    title = "DIE IRONMAN-HERAUSFORDERUNG",
    prefix = "IRONMAN: ",
    description = "Hardcore, keine Post, kein Auktionshaus, nur weiße oder graue Ausrüstung, keine Talente, keine Hauptberufe, keine Tränke, keine Gesundheitssteine, keine Essens- oder Schriftrollenstärkungen, keine externen Stärkungszauber, Selbstverstärkungszauber sind erlaubt.",
    cmdln_n = "Überprüft alle {N} Sekunden (Standard: 15)",
    cmdln_on_off = "Periodische Überprüfung starten/stoppen (standardmäßig aktiviert)",
    disclaimer = "Aufgrund der begrenzten WoW-API ist es schwierig zu bestimmen, ob ein Buff erlaubt ist oder nicht. Wenn jemand anderes dich bufft, kann das Addon dich darüber informieren; und es kann dich darauf hinweisen, Schriftrollen-Buffs zu entfernen. Buffs aus Alchemie kann es jedoch nicht erkennen. HOTs von anderen Spielern werden als Buffs betrachtet, das Addon wird dich also darüber informieren.",
    err_seconds_ij = function(i, j) return "Sekunden müssen zwischen " .. i .. " und " .. j .. " liegen" end,
    checking_every_n = function(n) return "Überprüfe nun alle " .. n .. " Sekunden" end,
    checking_on = "Überprüfung aktiviert",
    checking_off = "Überprüfung deaktiviert",
    init_checking_off_s = function(s) return "Initialisiert, Überprüfung deaktiviert, tippe " .. s .. ", um sie zu aktivieren" end,
    init_checking_on_n = function(n) return "Initialisiert, Überprüfung alle " .. n .. " Sekunden" end,
    type_s_for_more_info = function(s) return "Tippe " .. s .. " für weitere Informationen" end,
    err_unequip_s_s = function(slotname, link) return "Rüste den " .. slotname .. "-Slot aus " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Rüste verzauberten " .. slotname .. "-Slot aus " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "Du kannst " .. link .. " nicht benutzen" end,
    err_reset_talents = "Setze deine Talente zurück",
    err_unlearn_n_profs = function(n) return n==1 and ("Lerne deinen Hauptberuf ab") or ("Lerne deine Hauptberufe ab") end,
    err_buff_external = function(s) return "Entferne externen Buff: " .. s end,
    err_buff_disallowed = function(s) return "Entferne unerlaubten Buff: " .. s end,
    err_you_died = "Du bist gestorben",
    err_no_mail = "Ihr könnt die Post nicht benutzen",
    err_no_ah = "Ihr könnt das Auktionshaus nicht benutzen",
}

ns["esES"] = {
    SLOTS = {
        ammo = "munición",
        head = "cabeza",
        neck = "cuello",
        shoulder = "hombros",
        shirt = "camisa",
        chest = "pecho",
        waist = "cintura",
        legs = "piernas",
        feet = "pies",
        wrist = "muñecas",
        hands = "manos",
        finger0 = "dedo #1",
        finger1 = "dedo #2",
        trinket0 = "abrazadera #1",
        trinket1 = "abrazadera #2",
        back = "espalda",
        mainhand = "mano principal",
        secondaryhand = "mano secundaria",
        ranged = "a distancia",
        tabard = "tabardo",
    },

    SCROLL_BUFFS = { ["Bien Alimentado"]=1, ["Espíritu"]=1, ["Armadura"]=1, ["Intelecto"]=1, ["Agilidad"]=1, ["Aguante"]=1, ["Fuerza"]=1, },
    PRIMARY_PROFESSIONS = { ["Alquimia"]=1, ["Herrería"]=1, ["Encantamiento"]=1, ["Ingeniería"]=1, ["Herboristería"]=1, ["Inscripción"]=1, ["Joyería"]=1, ["Peletería"]=1, ["Minería"]=1, ["Desuello"]=1, ["Sastrería"]=1, },

    title = "EL DESAFÍO IRONMAN",
    prefix = "IRONMAN: ",
    description = "Hardcore, sin buzón, sin casa de subastas, solo equipo blanco o gris, sin talentos, sin profesiones primarias, sin pociones, sin piedras de salud, sin beneficios de comida o pergaminos, sin beneficios externos, los hechizos de beneficio propios están permitidos.",
    cmdln_n = "Comprueba cada {N} segundos (15 por defecto)",
    cmdln_on_off = "Iniciar/detener comprobación periódica (activada por defecto)",
    disclaimer = "Debido a la naturaleza limitada de la API de WoW, es difícil determinar si un buff es permitido o no. Si alguien más te aplica un buff, el addon puede informarte; y también puede indicarte que retires buffs de pergamino. Pero no puede advertir sobre buffs de alquimia. Los HOTs de otros jugadores se consideran buffs, por lo que el addon te avisará de ellos.",
    err_seconds_ij = function(i, j) return "Los segundos deben estar entre " .. i .. " y " .. j end,
    checking_every_n = function(n) return "Comprobando cada " .. n .. " segundos" end,
    checking_on = "Comprobación activada",
    checking_off = "Comprobación desactivada",
    init_checking_off_s = function(s) return "Inicializado, comprobación desactivada, escribe " .. s .. " para activarla" end,
    init_checking_on_n = function(n) return "Inicializado, comprobación cada " .. n .. " segundos" end,
    type_s_for_more_info = function(s) return "Escribe " .. s .. " para más información" end,
    err_unequip_s_s = function(slotname, link) return "Desequipar slot " .. slotname .. " " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Desequipar slot encantado " .. slotname .. " " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "No puedes usar " .. link end,
    err_reset_talents = "Reinicia tus talentos",
    err_unlearn_n_profs = function(n) return n==1 and ("Olvidar tu profesión principal") or ("Olvidar tus profesiones principales") end,
    err_buff_external = function(s) return "Eliminar buff externo: " .. s end,
    err_buff_disallowed = function(s) return "Eliminar buff no permitido: " .. s end,
    err_you_died = "Has muerto",
    err_no_mail = "No puedes usar el buzón",
    err_no_ah = "No puedes usar la casa de subastas",
}

-- esMX is functionally the same as esES, so just reuse the above tables.
ns["esMX"] = ns["esES"]

ns["frFR"] = {
    SLOTS = {
        ammo = "munition",
        head = "tête",
        neck = "cou",
        shoulder = "épaules",
        shirt = "chemise",
        chest = "torse",
        waist = "taille",
        legs = "jambes",
        feet = "pieds",
        wrist = "poignets",
        hands = "mains",
        finger0 = "doigt #1",
        finger1 = "doigt #2",
        trinket0 = "bijou #1",
        trinket1 = "bijou #2",
        back = "dos",
        mainhand = "main droite",
        secondaryhand = "main gauche",
        ranged = "distance",
        tabard = "tabard",
    },

    SCROLL_BUFFS = { ["Bien Nourri"]=1, ["Esprit"]=1, ["Armure"]=1, ["Intelligence"]=1, ["Agilité"]=1, ["Endurance"]=1, ["Force"]=1, },
    PRIMARY_PROFESSIONS = { ["Alchimie"]=1, ["Forge"]=1, ["Enchantement"]=1, ["Ingénierie"]=1, ["Herboristerie"]=1, ["Calligraphie"]=1, ["Joaillerie"]=1, ["Travail du cuir"]=1, ["Minage"]=1, ["Dépeçage"]=1, ["Couture"]=1, },

    title = "LE DÉFI IRONMAN",
    prefix = "IRONMAN : ",
    description = "Hardcore, pas de boîte aux lettres, pas d’hôtel des ventes, uniquement de l’équipement blanc ou gris, pas de talents, pas de professions principales, pas de potions, pas de pierres de soins, pas d’améliorations de nourriture ou de parchemins, pas de buffs externes, les sorts de renforcement personnels sont autorisés.",
    cmdln_n = "Vérifie toutes les {N} secondes (15 par défaut)",
    cmdln_on_off = "Activer/désactiver la vérification périodique (activée par défaut)",
    disclaimer = "En raison de la nature limitée de l'API WoW, il est difficile de déterminer si un buff donné est autorisé ou non. Si quelqu'un d'autre vous buffe, l'addon peut vous en informer ; il peut aussi vous indiquer de retirer les buffs de parchemin. Mais il ne peut pas avertir pour les buffs d'alchimie. Les HOTs d'autres joueurs sont considérés comme des buffs, donc l'addon vous en avertira.",
    err_seconds_ij = function(i, j) return "Les secondes doivent être entre " .. i .. " et " .. j end,
    checking_every_n = function(n) return "Vérification toutes les " .. n .. " secondes" end,
    checking_on = "Vérification activée",
    checking_off = "Vérification désactivée",
    init_checking_off_s = function(s) return "Initialisé, vérification désactivée, tapez " .. s .. " pour l'activer" end,
    init_checking_on_n = function(n) return "Initialisé, vérification toutes les " .. n .. " secondes" end,
    type_s_for_more_info = function(s) return "Tapez " .. s .. " pour plus d'informations" end,
    err_unequip_s_s = function(slotname, link) return "Déséquiper le slot " .. slotname .. " " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Déséquiper le slot enchanté " .. slotname .. " " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "Vous ne pouvez pas utiliser " .. link end,
    err_reset_talents = "Réinitialisez vos talents",
    err_unlearn_n_profs = function(n) return n==1 and ("Désapprendre votre profession principale") or ("Désapprendre vos professions principales") end,
    err_buff_external = function(s) return "Retirer le buff externe : " .. s end,
    err_buff_disallowed = function(s) return "Retirer le buff non autorisé : " .. s end,
    err_you_died = "Vous êtes mort",
    err_no_mail = "Vous ne pouvez pas utiliser la boîte aux lettres",
    err_no_ah = "Vous ne pouvez pas utiliser l’hôtel des ventes",
}

ns["itIT"] = {
    SLOTS = {
        ammo = "munizione",
        head = "testa",
        neck = "collo",
        shoulder = "spalle",
        shirt = "camicia",
        chest = "petto",
        waist = "vita",
        legs = "gambe",
        feet = "piedi",
        wrist = "polsi",
        hands = "mani",
        finger0 = "dito #1",
        finger1 = "dito #2",
        trinket0 = "gioiello #1",
        trinket1 = "gioiello #2",
        back = "schiena",
        mainhand = "mano principale",
        secondaryhand = "mano secondaria",
        ranged = "distanza",
        tabard = "tabard",
    },

    SCROLL_BUFFS = { ["Ben Nutrito"]=1, ["Spirito"]=1, ["Armatura"]=1, ["Intelletto"]=1, ["Agilità"]=1, ["Tempra"]=1, ["Forza"]=1, },
    PRIMARY_PROFESSIONS = { ["Alchimia"]=1, ["Forgiatura"]=1, ["Incantamento"]=1, ["Ingegneria"]=1, ["Erboristeria"]=1, ["Calligrafia"]=1, ["Gioielleria"]=1, ["Conciatura"]=1, ["Mineraria"]=1, ["Scuoiatura"]=1, ["Sartoria"]=1, },

    title = "LA SFIDA IRONMAN",
    prefix = "IRONMAN: ",
    description = "Hardcore, niente cassetta della posta, niente casa d’aste, solo equipaggiamento bianco o grigio, niente talenti, niente professioni principali, niente pozioni, niente pietre della salute, niente benefici da cibo o pergamene, niente benefici esterni, gli incantesimi di auto-potenziamento sono consentiti.",
    cmdln_n = "Controlla ogni {N} secondi (15 di default)",
    cmdln_on_off = "Avvia/interrompi il controllo periodico (attivo di default)",
    disclaimer = "A causa delle limitazioni dell'API di WoW, è difficile determinare se un buff sia consentito o meno. Se qualcun altro ti applica un buff, l'addon può avvisarti; e può anche dirti di rimuovere i buff da pergamena. Ma non può avvisare sui buff derivanti dall'alchimia. Gli HOT da altri giocatori sono considerati buff, quindi l'addon ti avviserà.",
    err_seconds_ij = function(i,j) return "I secondi devono essere tra "..i.." e "..j end,
    checking_every_n = function(n) return "Controllo ogni "..n.." secondi" end,
    checking_on = "Controllo attivo",
    checking_off = "Controllo disattivato",
    init_checking_off_s = function(s) return "Inizializzato, controllo disattivato, digita "..s.." per attivarlo" end,
    init_checking_on_n = function(n) return "Inizializzato, controllo ogni "..n.." secondi" end,
    type_s_for_more_info = function(s) return "Digita "..s.." per maggiori informazioni" end,
    err_unequip_s_s = function(slotname, link) return "Desequipaggia slot "..slotname.." "..(link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Desequipaggia slot incantato "..slotname.." "..(link or '') end,
    err_you_cannot_use_s = function(link) return "Non puoi usare "..link end,
    err_reset_talents = "Reimposta i tuoi talenti",
    err_unlearn_n_profs = function(n) return n==1 and ("Dimentica la tua professione primaria") or ("Dimentica le tue professioni primarie") end,
    err_buff_external = function(s) return "Rimuovi buff esterno: "..s end,
    err_buff_disallowed = function(s) return "Rimuovi buff non consentito: "..s end,
    err_you_died = "Sei morto",
    err_no_mail = "Non puoi usare la cassetta della posta",
    err_no_ah = "Non puoi usare la casa d’aste",
}

ns["ruRU"] = {
    SLOTS = {
        ammo = "патроны",
        head = "голова",
        neck = "шея",
        shoulder = "плечи",
        shirt = "рубашка",
        chest = "грудь",
        waist = "талия",
        legs = "ноги",
        feet = "стопы",
        wrist = "запястья",
        hands = "руки",
        finger0 = "палец #1",
        finger1 = "палец #2",
        trinket0 = "украшение #1",
        trinket1 = "украшение #2",
        back = "спина",
        mainhand = "основная рука",
        secondaryhand = "вторая рука",
        ranged = "дальний бой",
        tabard = "накидка",
    },

    SCROLL_BUFFS = { ["Сытость"]=1, ["Дух"]=1, ["Броня"]=1, ["Интеллект"]=1, ["Ловкость"]=1, ["Выносливость"]=1, ["Сила"]=1, },
    PRIMARY_PROFESSIONS = { ["Алхимия"]=1, ["Кузнечное дело"]=1, ["Наложение чар"]=1, ["Инженерное дело"]=1, ["Травничество"]=1, ["Начертание"]=1, ["Ювелирное дело"]=1, ["Кожевничество"]=1, ["Горное дело"]=1, ["Снятие шкур"]=1, ["Портняжное дело"]=1, },

    title = "ВЫЗОВ IRONMAN",
    prefix = "IRONMAN: ",
    description = "Хардкор: нельзя пользоваться почтовым ящиком, нельзя пользоваться аукционным домом, только белое или серое снаряжение, без талантов, без основных профессий, без зелий, без камней здоровья, без эффектов еды или свитков, без внешних баффов, заклинания самобаффа разрешены.",
    cmdln_n = "Проверка каждые {N} секунд (по умолчанию 15)",
    cmdln_on_off = "Включить/выключить периодическую проверку (по умолчанию включена)",
    disclaimer = "Из-за ограничений API WoW сложно определить, допустим ли данный бафф. Если кто-то другой наложил на вас бафф, аддон сообщит об этом; он также может указать удалить баффы от свитков. Но он не может предупреждать о баффах от алхимии. HOT от других игроков считается баффом, поэтому аддон предупредит о них.",
    err_seconds_ij = function(i,j) return "Секунды должны быть между "..i.." и "..j end,
    checking_every_n = function(n) return "Проверка каждые "..n.." секунд" end,
    checking_on = "Проверка включена",
    checking_off = "Проверка отключена",
    init_checking_off_s = function(s) return "Инициализировано, проверка отключена, введите "..s.." для включения" end,
    init_checking_on_n = function(n) return "Инициализировано, проверка каждые "..n.." секунд" end,
    type_s_for_more_info = function(s) return "Введите "..s.." для получения дополнительной информации" end,
    err_unequip_s_s = function(slotname, link) return "Сними предмет из слота "..slotname.." "..(link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "Сними зачарованный предмет из слота "..slotname.." "..(link or '') end,
    err_you_cannot_use_s = function(link) return "Вы не можете использовать "..link end,
    err_reset_talents = "Сбросьте ваши таланты",
    err_unlearn_n_profs = function(n) return n==1 and ("Откажитесь от своей основной профессии") or ("Откажитесь от своих основных профессий") end,
    err_buff_external = function(s) return "Убрать внешний бафф: "..s end,
    err_buff_disallowed = function(s) return "Убрать недопустимый бафф: "..s end,
    err_you_died = "Вы умерли",
    err_no_mail = "Вы не можете пользоваться почтовым ящиком",
    err_no_ah = "Вы не можете пользоваться аукционным домом",
}

ns["zhTW"] = {
    SLOTS = {
        ammo = "彈藥",
        head = "頭部",
        neck = "頸部",
        shoulder = "肩膀",
        shirt = "襯衣",
        chest = "胸部",
        waist = "腰部",
        legs = "腿部",
        feet = "腳部",
        wrist = "手腕",
        hands = "手部",
        finger0 = "手指 #1",
        finger1 = "手指 #2",
        trinket0 = "飾品 #1",
        trinket1 = "飾品 #2",
        back = "背部",
        mainhand = "主手",
        secondaryhand = "副手",
        ranged = "遠程",
        tabard = "外袍",
    },

    SCROLL_BUFFS = { ["吃飽了"]=1, ["精神"]=1, ["護甲"]=1, ["智力"]=1, ["敏捷"]=1, ["耐力"]=1, ["力量"]=1, },
    PRIMARY_PROFESSIONS = { ["煉金術"]=1, ["鍛造"]=1, ["附魔"]=1, ["工程學"]=1, ["草藥學"]=1, ["銘文學"]=1, ["珠寶設計"]=1, ["製皮"]=1, ["採礦"]=1, ["剝皮"]=1, ["裁縫"]=1, },

    title = "鐵人挑戰",
    prefix = "鐵人：",
    description = "硬核：不能使用信箱，不能使用拍賣場，只能穿白色或灰色裝備，不能點天賦，不能學主要專業，不能使用藥水，不能使用治療石，不能使用食物或卷軸增益，不能有外部增益，自身的增益法術可以。",
    cmdln_n = "每 {N} 秒檢查一次 (預設為 15 秒)",
    cmdln_on_off = "開始/停止定期檢查 (預設為開啟)",
    disclaimer = "由於魔獸世界 API 的限制，很難完全判斷某個增益是否允許。若是其他人給你增益，本插件會警告；若是卷軸增益，也會提示你移除。但無法檢測藥劑類增益。其他玩家的持續治療效果 (HOT) 也視為增益，因此會提示你移除。",
    err_seconds_ij = function(i, j) return "秒數必須介於 " .. i .. " 和 " .. j end,
    checking_every_n = function(n) return "現在每 " .. n .. " 秒檢查一次" end,
    checking_on = "檢查中",
    checking_off = "檢查已關閉",
    init_checking_off_s = function(s) return "初始化完成，檢查已關閉，輸入 " .. s .. " 可開啟" end,
    init_checking_on_n = function(n) return "初始化完成，每 " .. n .. " 秒檢查一次" end,
    type_s_for_more_info = function(s) return "輸入 " .. s .. " 以取得更多資訊" end,
    err_unequip_s_s = function(slotname, link) return "請卸下 " .. slotname .. " 欄位 " .. (link or '') end,
    err_unequip_enchanted_s_s = function(slotname, link) return "請卸下附魔的 " .. slotname .. " 欄位 " .. (link or '') end,
    err_you_cannot_use_s = function(link) return "你不能使用 " .. link end,
    err_reset_talents = "請重置你的天賦",
    err_unlearn_n_profs = function(n) return n==1 and ("請遺忘你的主要專業") or ("請遺忘你的主要專業") end,
    err_buff_external = function(s) return "移除外部增益：" .. s end,
    err_buff_disallowed = function(s) return "移除不允許的增益：" .. s end,
    err_you_died = "你已經死亡",
    err_no_mail = "你不能使用信箱",
    err_no_ah = "你不能使用拍賣場",
}

ns["koKR"] = {
    SLOTS = {
        ammo = "탄약",
        head = "머리",
        neck = "목",
        shoulder = "어깨",
        shirt = "속옷",
        chest = "가슴",
        waist = "허리",
        legs = "다리",
        feet = "발",
        wrist = "손목",
        hands = "손",
        finger0 = "손가락 #1",
        finger1 = "손가락 #2",
        trinket0 = "장신구 #1",
        trinket1 = "장신구 #2",
        back = "등",
        mainhand = "주장비",
        secondaryhand = "보조장비",
        ranged = "원거리",
        tabard = "겉옷",
    },

    SCROLL_BUFFS = { ["Well Fed"]="포만감", ["Spirit"]="정신력", ["Armor"]="방어도", ["Intellect"]="지능", ["Agility"]="민첩성", ["Stamina"]="체력", ["Strength"]="힘" },
    PRIMARY_PROFESSIONS = { ["연금술"]=1, ["대장기술"]=1, ["마법부여"]=1, ["기계공학"]=1, ["약초채집"]=1, ["주문각인"]=1, ["보석세공"]=1, ["가죽세공"]=1, ["채광"]=1, ["무두질"]=1, ["재봉술"]=1, },

    title = "철인 도전",
    prefix = "철인: ",
    description = "하드코어: 우편 불가, 경매장 불가, 흰색 또는 회색 장비만 사용, 특성 불가, 주요 전문 기술 불가, 물약 불가, 생명석 불가, 음식/두루마리 버프 불가, 외부 버프 불가, 자기 강화 주문은 허용.",
    cmdln_n = "{N}초마다 확인합니다 (기본값 15초)",
    cmdln_on_off = "주기적인 확인 시작/중지 (기본값은 시작)",
    disclaimer = "WoW API의 제한으로 인해 특정 버프가 허용되는지 완전히 구분하기 어렵습니다. 다른 플레이어가 버프를 줄 경우 애드온이 알려줄 수 있고, 두루마리 버프는 제거하라고 경고할 수 있습니다. 그러나 연금술 버프는 감지할 수 없습니다. 다른 플레이어의 HOT(지속 치유)는 버프로 간주되므로 경고가 표시됩니다.",
    err_seconds_ij = function(i, j) return "초는 " .. i .. "에서 " .. j .. " 사이여야 합니다" end,
    checking_every_n = function(n) return "이제 " .. n .. "초마다 확인합니다" end,
    checking_on = "확인 중",
    checking_off = "확인 중지",
    init_checking_off_s = function(s) return "초기화 완료, 확인 꺼짐, " .. s .. " 입력 시 켜짐" end,
    init_checking_on_n = function(n) return "초기화 완료, " .. n .. "초마다 확인" end,
    type_s_for_more_info = function(s) return s .. " 입력 시 자세한 정보 표시" end,
    err_unequip_s_s = function(slotname, link) return slotname .. " 슬롯의 " .. (link or '') .. " 장비를 벗으세요" end,
    err_unequip_enchanted_s_s = function(slotname, link) return "마법부여된 " .. slotname .. " 슬롯의 " .. (link or '') .. " 장비를 벗으세요" end,
    err_you_cannot_use_s = function(link) return link .. "을(를) 사용할 수 없습니다" end,
    err_reset_talents = "특성을 초기화하세요",
    err_unlearn_n_profs = function(n) return n==1 and ("주요 전문 기술을 잊으세요") or ("주요 전문 기술을 잊으세요") end,
    err_buff_external = function(s) return "외부 버프 제거: " .. s end,
    err_buff_disallowed = function(s) return "허용되지 않는 버프 제거: " .. s end,
    err_you_died = "당신은 사망했습니다",
    err_no_mail = "우편을 사용할 수 없습니다",
    err_no_ah = "경매장을 사용할 수 없습니다",
}
